services:
  mytools-app:
    build: .
    container_name: mytools-app
    restart: always
    expose:
      - "8000"
    environment:
      - VITE_API_URL=https://mytools.appeul.com
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
    networks:
      - web-proxy

networks:
  web-proxy:
    external: true

